export enum Language {
    Afrikaans = 'af',
    Albanian = 'sq',
    Basque = 'eu',
    Belarusian = 'be',
    Bulgarian = 'bg',
    Catalan = 'ca',
    ChineseSimplified = 'zh_CN',
    ChineseTraditional = 'zh_TW',
    Croatian = 'hr',
    Czech = 'cs',
    Danish = 'da',
    Dutch = 'nl',
    English = 'en',
    Estonian = 'et',
    Filipino = 'fil',
    Finnish = 'fi',
    French = 'fr',
    Galician = 'gl',
    German = 'de',
    Greek = 'el',
    Haitian = 'ht',
    Hindi = 'hi',
    Hungarian = 'hu',
    Icelandic = 'is',
    Indonesian = 'id',
    Irish = 'ga',
    Italian = 'it',
    Japanese = 'ja',
    Korean = 'ko',
    Latin = 'la',
    Latvian = 'lv',
    Lithuanian = 'lt',
    Macedonian = 'mk',
    Malay = 'ms',
    Norwegian = 'no',
    Polish = 'pl',
    PortugueseBrazil = 'pt_BR',
    PortuguesePortugal = 'pt_PT',
    Romanian = 'ro',
    Russian = 'ru',
    Serbian = 'sr',
    Slovak = 'sk',
    Slovenian = 'sl',
    Spanish = 'es',
    Swahili = 'sw',
    Swedish = 'sv',
    Thai = 'th',
    Turkish = 'tr',
    Ukranian = 'yk',
    Vietnamese = 'vi',
    Welsh = 'cy',
}

export const LanguageToLabelMapping: Record<Language, string> = {
    [Language.Afrikaans]: 'Afrikaans',
    [Language.Albanian]: 'Albanian',
    [Language.Basque]: 'Basque',
    [Language.Belarusian]: 'Belarusian',
    [Language.Bulgarian]: 'Bulgarian',
    [Language.Catalan]: 'Catalan',
    [Language.ChineseSimplified]: 'Chinese (Simplified)',
    [Language.ChineseTraditional]: 'Chinese (Traditional)',
    [Language.Croatian]: 'Croatian',
    [Language.Czech]: 'Czech',
    [Language.Danish]: 'Danish',
    [Language.Dutch]: 'Dutch',
    [Language.English]: 'English',
    [Language.Estonian]: 'Estonian',
    [Language.Filipino]: 'Filipino',
    [Language.Finnish]: 'Finnish',
    [Language.French]: 'French',
    [Language.Galician]: 'Galician',
    [Language.German]: 'German',
    [Language.Greek]: 'Greek',
    [Language.Haitian]: 'Haitian',
    [Language.Hindi]: 'Hindi',
    [Language.Hungarian]: 'Hungarian',
    [Language.Icelandic]: 'Icelandic',
    [Language.Indonesian]: 'Indonesian',
    [Language.Irish]: 'Irish',
    [Language.Italian]: 'Italian',
    [Language.Japanese]: 'Japanese',
    [Language.Korean]: 'Korean',
    [Language.Latin]: 'Latin',
    [Language.Latvian]: 'Latvian',
    [Language.Lithuanian]: 'Lithuanian',
    [Language.Macedonian]: 'Macedonian',
    [Language.Malay]: 'Malay',
    [Language.Norwegian]: 'Norwegian',
    [Language.Polish]: 'Polish',
    [Language.PortugueseBrazil]: 'Portuguese (Brazil)',
    [Language.PortuguesePortugal]: 'Portuguese (Portugal)',
    [Language.Romanian]: 'Romanian',
    [Language.Russian]: 'Russian',
    [Language.Serbian]: 'Serbian',
    [Language.Slovak]: 'Slovak',
    [Language.Slovenian]: 'Slovenian',
    [Language.Spanish]: 'Spanish',
    [Language.Swahili]: 'Swahili',
    [Language.Swedish]: 'Swedish',
    [Language.Thai]: 'Thai',
    [Language.Turkish]: 'Turkish',
    [Language.Ukranian]: 'Ukranian',
    [Language.Vietnamese]: 'Vietnamese',
    [Language.Welsh]: 'Welsh',
};